FROM node:16

RUN mkdir -p /app/node_modules && chown -R node:node /app

WORKDIR /app

COPY package*.json yarn.lock ./

USER node

RUN yarn install

COPY --chown=node:node . .

RUN yarn build

EXPOSE 3000

CMD yarn dev